-- name: p2_text_pattern_breakdown
-- server: aws-luckyus-iriskcontrolservice-rw (via MCP server mcp-db-gateway)
-- purpose: P2: which pattern the flagged config values match (counts only)
-- kind: agg; windows: 1
-- params: {}
-- run (NY): 2026-09-27 06:39

SELECT /*+ MAX_EXECUTION_TIME(10000) */ x.* FROM (
SELECT 't_rms_engine_rule' AS table_name, 'rule_name' AS column_name, SUM(rule_name REGEXP '[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}') AS ipv4_full, SUM(rule_name REGEXP '(^|[^0-9.])[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}([^0-9.]|$)') AS ipv4_c_segment, SUM(rule_name REGEXP '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}') AS email, SUM(rule_name REGEXP '[0-9]{7,}') AS digits7plus, SUM(rule_name REGEXP '(^|[^0-9])20[2-3][0-9][01][0-9][0-3][0-9]([^0-9]|$)') AS date8_2026, SUM(rule_name REGEXP '[0-9]{9,}') AS digits9plus, SUM(rule_name REGEXP '://') AS url, SUM(rule_name REGEXP '[A-Za-z0-9-]+\\.(com|net|org|io|us|cn|internal|local|aws)\\b') AS hostname, SUM(rule_name REGEXP '[A-Za-z0-9.-]+:[0-9]{2,5}') AS hostport FROM luckyus_iriskcontrolservice.t_rms_engine_rule
UNION ALL
SELECT 't_rms_engine_rule' AS table_name, 'condition_value' AS column_name, SUM(condition_value REGEXP '[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}') AS ipv4_full, SUM(condition_value REGEXP '(^|[^0-9.])[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}([^0-9.]|$)') AS ipv4_c_segment, SUM(condition_value REGEXP '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}') AS email, SUM(condition_value REGEXP '[0-9]{7,}') AS digits7plus, SUM(condition_value REGEXP '(^|[^0-9])20[2-3][0-9][01][0-9][0-3][0-9]([^0-9]|$)') AS date8_2026, SUM(condition_value REGEXP '[0-9]{9,}') AS digits9plus, SUM(condition_value REGEXP '://') AS url, SUM(condition_value REGEXP '[A-Za-z0-9-]+\\.(com|net|org|io|us|cn|internal|local|aws)\\b') AS hostname, SUM(condition_value REGEXP '[A-Za-z0-9.-]+:[0-9]{2,5}') AS hostport FROM luckyus_iriskcontrolservice.t_rms_engine_rule
UNION ALL
SELECT 't_rms_engine_rule' AS table_name, 'rule_express' AS column_name, SUM(rule_express REGEXP '[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}') AS ipv4_full, SUM(rule_express REGEXP '(^|[^0-9.])[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}([^0-9.]|$)') AS ipv4_c_segment, SUM(rule_express REGEXP '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}') AS email, SUM(rule_express REGEXP '[0-9]{7,}') AS digits7plus, SUM(rule_express REGEXP '(^|[^0-9])20[2-3][0-9][01][0-9][0-3][0-9]([^0-9]|$)') AS date8_2026, SUM(rule_express REGEXP '[0-9]{9,}') AS digits9plus, SUM(rule_express REGEXP '://') AS url, SUM(rule_express REGEXP '[A-Za-z0-9-]+\\.(com|net|org|io|us|cn|internal|local|aws)\\b') AS hostname, SUM(rule_express REGEXP '[A-Za-z0-9.-]+:[0-9]{2,5}') AS hostport FROM luckyus_iriskcontrolservice.t_rms_engine_rule
UNION ALL
SELECT 't_rms_engine_strategy' AS table_name, 'strategy_name' AS column_name, SUM(strategy_name REGEXP '[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}') AS ipv4_full, SUM(strategy_name REGEXP '(^|[^0-9.])[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}([^0-9.]|$)') AS ipv4_c_segment, SUM(strategy_name REGEXP '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}') AS email, SUM(strategy_name REGEXP '[0-9]{7,}') AS digits7plus, SUM(strategy_name REGEXP '(^|[^0-9])20[2-3][0-9][01][0-9][0-3][0-9]([^0-9]|$)') AS date8_2026, SUM(strategy_name REGEXP '[0-9]{9,}') AS digits9plus, SUM(strategy_name REGEXP '://') AS url, SUM(strategy_name REGEXP '[A-Za-z0-9-]+\\.(com|net|org|io|us|cn|internal|local|aws)\\b') AS hostname, SUM(strategy_name REGEXP '[A-Za-z0-9.-]+:[0-9]{2,5}') AS hostport FROM luckyus_iriskcontrolservice.t_rms_engine_strategy
) x
